openapi: 3.1.0
info:
  title: "API BrokerAssistant"
  version: "1.0.0"
  description: |
    **BrokerAssistant API** предоставляет функционал для управления лотами на торгах по банкротству, 
    взаимодействия между брокерами и инвесторами, а также распределения прибыли. 
    
    🔐 **Безопасность и авторизация:**
    - Авторизация реализована через **JWT-токены, передаваемые в `HttpOnly`-cookie**.
    - Для аутентификации необходимо **выполнить логин (`/auth/login`)**, после чего токен автоматически отправляется в запросах.
    - Фронтенд должен отправлять запросы с `withCredentials: true`, чтобы браузер автоматически передавал `accessToken`.
    - Обновление `accessToken` выполняется через `refreshToken` (`/auth/refresh`).
    - Для выхода из системы вызывается `/auth/logout`, удаляющий сессионные токены.
    
    📄 **Документация API:**
    - Полный список эндпоинтов доступен в разделе **"Paths"**.
    - Описание параметров запросов находится в **"Schemas"**.
servers:
  - url: "https://api.brokerassistant.com"
    description: "Production server"
  - url: "http://localhost:8080"
    description: "Development server"
tags:
  - name: "Auth"
    description: "Методы аутентификации"
  - name: "Users"
    description: "Методы работы с пользователями"
  - name: "Lots"
    description: "Методы управления лотами"
  - name: "Members"
    description: "Управление участниками лотов"
  - name: "Transactions"
    description: "Финансовые транзакции"
  - name: "Expenses"
    description: "Учет расходов"
  - name: "Financials"
    description: "Финансовый учет по лотам"
  - name: "Analytics"
    description: "Аналитические данные"
security:
  - SessionJWT: []

paths:
  /auth/register:
    post:
      summary: "Регистрация брокера"
      security: []
      tags:
        - "Auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                name:
                  type: string
      responses:
        "201":
          description: "Брокер успешно зарегистрирован"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        type: "null"
                      error:
                        type: "null"
                      meta:
                        type: "null"
        "400":
          description: "Ошибка валидации"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      success:
                        type: boolean
                        enum: [ false ]
                      data:
                        type: "null"
                      meta:
                        type: "null"

  /auth/login:
    post:
      summary: "Вход в систему"
      security: []
      tags:
        - "Auth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        "201":
          description: "Успешный вход в систему"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      data:
                        type: object
                        properties:
                          user:
                            $ref: "#/components/schemas/User"
                          token:
                            type: string
                      error:
                        type: "null"
                      meta:
                        type: "null"
        "400":
          description: "Ошибка валидации"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/BaseResponse"
                  - type: object
                    properties:
                      success:
                        type: boolean
                        enum: [ false ]
                      data:
                        type: "null"
                      meta:
                        type: "null"

  /users/me:
    get:
      summary: "Получить данные текущего пользователя"
      tags:
        - "Users"
      responses:
        "200":
          description: "Данные пользователя"

    patch:
      summary: "Обновить данные профиля"
      tags:
        - "Users"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
      responses:
        "200":
          description: "Профиль успешно обновлен"

  /lots:
    get:
      summary: "Получить список лотов"
      tags:
        - "Lots"
      responses:
        "200":
          description: "Список лотов"

    post:
      summary: "Создать новый лот"
      tags:
        - "Lots"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                lot_number:
                  type: string
                purchase_price:
                  type: number
                sale_price:
                  type: number
      responses:
        "201":
          description: "Лот успешно создан"

  /lots/{lot_id}/members:
    get:
      summary: "Получить список участников лота"
      tags:
        - "Members"
      parameters:
        - name: lot_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Список участников"

    post:
      summary: "Добавить участника в лот"
      tags:
        - "Members"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                member_id:
                  type: string
                share_percent:
                  type: number
      responses:
        "201":
          description: "Участник успешно добавлен"

  /lots/{lot_id}/transactions:
    get:
      summary: "Получить список транзакций по лоту"
      tags:
        - "Transactions"
      parameters:
        - name: lot_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Список транзакций"

  /lots/{lot_id}/expenses:
    get:
      summary: "Получить список расходов по лоту"
      tags:
        - "Expenses"
      parameters:
        - name: lot_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Список расходов"

    post:
      summary: "Добавить расход"
      tags:
        - "Expenses"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                amount:
                  type: number
      responses:
        "201":
          description: "Расход успешно добавлен"

  /lots/{lot_id}/financials:
    get:
      summary: "Получить финансовые итоги по лоту"
      tags:
        - "Financials"
      parameters:
        - name: lot_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Финансовые итоги"

  /analytics/dashboard:
    get:
      summary: "Получить общую статистику"
      tags:
        - "Analytics"
      responses:
        "200":
          description: "Данные аналитики"

components:
  securitySchemes:
    SessionCookiesJWT:
      type: apiKey
      in: cookie
      name: access_token
      description: "JWT токен доступа, сохраненный в cookie с флагом HttpOnly"

  schemas:
    BaseResponse:
      type: object
      properties:
        success:
          type: boolean
          description: "Флаг успешности запроса (`true` — запрос выполнен успешно, `false` — произошла ошибка)"
        message:
          type: string
          description: "Краткое описание результата"
        data:
          type: object
          nullable: true
          description: "Основные данные ответа. Может быть объектом или `null`"
        error:
          nullable: true
          description: "Информация об ошибке (присутствует, если `success: false`)"
          $ref: '#/components/schemas/Error'
        meta:
          nullable: true
          description: "Дополнительные данные, например, информация о пагинации"
          $ref: '#/components/schemas/Meta'

    Error:
      type: object
      properties:
        code:
          type: integer
          description: "HTTP-код ошибки (например, 400, 404 и т.д.)"
        message:
          type: string
          description: "Сообщение об ошибке"
        details:
          type: array
          nullable: true
          description: "Список дополнительных деталей об ошибке. Используется при валидации."
          items:
            type: object
            properties:
              field:
                type: string
                description: "Название поля, вызвавшего ошибку"
              message:
                type: string
                description: "Сообщение о проблеме с этим полем"

    Meta:
      type: object

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор пользователя
        email:
          type: string
          format: email
          description: Адрес электронной почты пользователя
        name:
          type: string
          description: Имя пользователя
        is_broker:
          type: boolean
          description: Указывает, является ли пользователь брокером
        created_at:
          type: string
          format: date-time
          description: Время создания пользователя

    Lot:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор лота
        broker_id:
          type: string
          format: uuid
          description: Идентификатор брокера (ссылка на пользователя)
        name:
          type: string
          description: Название лота
        lot_number:
          type: string
          nullable: true
          description: Номер лота
        status:
          type: string
          enum:
            - purchased
            - renovation
            - hold
            - listed_for_sale
            - sold
            - closed
          description: Статус лота
        purchase_price:
          type: number
          format: double
          description: Цена покупки лота
        sale_price:
          type: number
          format: double
          description: Цена продажи лота
        broker_commission_percent:
          type: number
          format: double
          description: Процент комиссии брокера
        broker_tax_percent:
          type: number
          format: double
          description: Процент налога с брокера
        purchase_date:
          type: string
          format: date
          description: Дата покупки лота
        updated_at:
          type: string
          format: date-time
          description: Время последнего обновления записи
        created_at:
          type: string
          format: date-time
          description: Время создания записи
      required:
        - id
        - broker_id
        - name
        - status
        - purchase_price
        - purchase_date
        - updated_at
        - created_at

    LotStatusHistory:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор записи истории статуса лота
        lot_id:
          type: string
          format: uuid
          description: Идентификатор лота
        status:
          type: string
          enum:
            - purchased
            - renovation
            - hold
            - listed_for_sale
            - sold
            - closed
          description: Статус лота
        created_at:
          type: string
          format: date-time
          description: Дата создания записи
      required:
        - id
        - lot_id
        - status
        - created_at

    LotMember:
      type: object
      properties:
        lot_id:
          type: string
          format: uuid
          description: Идентификатор лота
        member_id:
          type: string
          format: uuid
          nullable: true
          description: Идентификатор участника
        referral_member_id:
          type: string
          format: uuid
          nullable: true
          description: Идентификатор реферального участника
        share_percent:
          type: number
          format: double
          description: Доля участника (%) в лоте
        referral_fee_percent:
          type: number
          format: double
          description: Процент реферальной комиссии
      required:
        - lot_id
        - share_percent

    LotExpense:
      type: object
      properties:
        lot_id:
          type: string
          format: uuid
          description: Идентификатор лота
        transaction_id:
          type: string
          format: uuid
          description: Идентификатор транзакции
        description:
          type: string
          description: Описание расходов
      required:
        - lot_id
        - transaction_id
        - description

    LotTransaction:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор транзакции
        lot_id:
          type: string
          format: uuid
          description: Идентификатор лота
        user_id:
          type: string
          format: uuid
          nullable: true
          description: Идентификатор пользователя, связанного с транзакцией
        type:
          type: string
          enum:
            - investment
            - payout
            - broker_commission
            - broker_tax
            - referral_fee
            - expense
          description: Тип транзакции
        amount:
          type: number
          format: double
          description: Сумма транзакции
        updated_at:
          type: string
          format: date-time
          description: Время последнего изменения записи
        created_at:
          type: string
          format: date-time
          description: Время создания записи
      required:
        - id
        - lot_id
        - type
        - amount
        - updated_at
        - created_at

    LotFinancials:
      type: object
      properties:
        lot_id:
          type: string
          format: uuid
          description: Идентификатор лота
        purchase_price:
          type: number
          format: double
          description: Цена покупки лота
        sale_price:
          type: number
          format: double
          description: Цена продажи лота
        gross_profit:
          type: number
          format: double
          description: Валовая прибыль
        net_profit:
          type: number
          format: double
          description: Чистая прибыль
        broker_commission:
          type: number
          format: double
          description: Комиссия брокера
        broker_tax:
          type: number
          format: double
          description: Налог брокера
        total_investments:
          type: number
          format: double
          description: Общая сумма инвестиций
        total_payouts:
          type: number
          format: double
          description: Общая сумма выплат
        total_referral_fees:
          type: number
          format: double
          description: Общая сумма реферальных вознаграждений
        created_at:
          type: string
          format: date-time
          description: Дата создания записи
      required:
        - lot_id
        - purchase_price
        - sale_price
        - gross_profit
        - net_profit
        - created_at